# Generated by Django 4.1.5 on 2023-01-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="tipo",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
