# Generated by Django 4.2.7 on 2023-12-13 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="linhadeproduto",
            old_name="preço",
            new_name="preco",
        ),
    ]
