# Generated by Django 4.2.7 on 2023-12-03 18:03

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_categoria_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="is_active",
            field=models.BooleanField(default=True, help_text="Produto ativo"),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nome",
            field=models.CharField(
                help_text="Nome da categoria", max_length=80, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text="Categoria pai",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="product.categoria",
            ),
        ),
        migrations.AlterField(
            model_name="marca",
            name="nome",
            field=models.CharField(help_text="Nome da marca", max_length=80),
        ),
        migrations.AlterField(
            model_name="produto",
            name="categoria",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text="Categoria do produto",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.categoria",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="descricao",
            field=models.TextField(blank=True, help_text="Descrição do produto"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="is_digital",
            field=models.BooleanField(default=False, help_text="Produto digital"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="marca",
            field=models.ForeignKey(
                help_text="Marca do produto",
                on_delete=django.db.models.deletion.CASCADE,
                to="product.marca",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="nome",
            field=models.CharField(help_text="Nome do produto", max_length=80),
        ),
        migrations.AlterField(
            model_name="produto",
            name="tipo",
            field=models.CharField(
                blank=True, help_text="Tipo do produto", max_length=10, null=True
            ),
        ),
    ]
