# Generated by Django 4.2.7 on 2023-12-16 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_produtoimagem_delete_produtoimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Atributo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome do atributo", max_length=80, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Descrição do atributo"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AtributoValor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "att_valor",
                    models.CharField(
                        help_text="Valor do atributo",
                        max_length=80,
                        unique=True,
                        verbose_name="Valor do atributo",
                    ),
                ),
                (
                    "atributo",
                    models.ForeignKey(
                        help_text="Atributo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atributo_valor",
                        to="product.atributo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AtributoLinhaDeProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Está ativo?"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Data de criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Data de atualização"
                    ),
                ),
                (
                    "atributo_valor",
                    models.ForeignKey(
                        help_text="Valor do atributo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atributo_linha_de_produto_valor",
                        to="product.atributovalor",
                    ),
                ),
                (
                    "linha_de_produto",
                    models.ForeignKey(
                        help_text="Linha de produto",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atributo_linha_de_produto",
                        to="product.linhadeproduto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atributo de linha de produto",
                "verbose_name_plural": "Atributos de linha de produto",
                "unique_together": {("linha_de_produto", "atributo_valor")},
            },
        ),
        migrations.AddField(
            model_name="linhadeproduto",
            name="atributos",
            field=models.ManyToManyField(
                help_text="Atributos da linha de produto",
                related_name="atributos_linha_de_produto",
                through="product.AtributoLinhaDeProduto",
                to="product.atributovalor",
            ),
        ),
    ]
