# Generated by Django 4.2.7 on 2023-12-03 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_produto_is_active_alter_categoria_nome_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinhaDeProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preço",
                    models.DecimalField(
                        decimal_places=2, help_text="Preço do produto", max_digits=10
                    ),
                ),
                ("sku", models.CharField(help_text="Código do produto", max_length=80)),
                ("estoque", models.IntegerField(help_text="Quantidade em estoque")),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Linha de produto ativa"
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        help_text="Produto",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.produto",
                    ),
                ),
            ],
        ),
    ]
