# Generated by Django 4.2.7 on 2023-12-17 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_remove_atributolinhadeproduto_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoDeProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome do tipo de produto", max_length=80
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="atributovalor",
            options={
                "verbose_name": "Valor do atributo",
                "verbose_name_plural": "Valores do atributo",
            },
        ),
        migrations.AddField(
            model_name="linhadeproduto",
            name="produto_tipo",
            field=models.ForeignKey(
                blank=True,
                help_text="Tipo de produto",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="product.tipodeproduto",
            ),
        ),
    ]
