# Generated by Django 4.2.7 on 2023-12-17 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_tipodeproduto_alter_atributovalor_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoDeProdutoAtributos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "atributo",
                    models.ForeignKey(
                        help_text="Atributo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tipo_de_produto_atributos_at",
                        to="product.atributo",
                    ),
                ),
                (
                    "tipo_de_produto",
                    models.ForeignKey(
                        help_text="Tipo de produto",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tipo_de_produto_atributos_tp",
                        to="product.tipodeproduto",
                    ),
                ),
            ],
            options={
                "unique_together": {("atributo", "tipo_de_produto")},
            },
        ),
        migrations.AddField(
            model_name="tipodeproduto",
            name="atributo",
            field=models.ManyToManyField(
                help_text="Atributo",
                related_name="tipo_de_produto_atributos",
                through="product.TipoDeProdutoAtributos",
                to="product.atributo",
            ),
        ),
    ]
