# Generated by Django 4.2.7 on 2023-12-17 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_tipodeprodutoatributos_tipodeproduto_atributo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tipodeprodutoatributos",
            name="tipo_de_produto",
            field=models.ForeignKey(
                help_text="Tipo de produto",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tipo_de_produto_atributos_tp",
                to="product.tipodeproduto",
                verbose_name="Tipo de produto",
            ),
        ),
    ]
