# Generated by Django 4.2.7 on 2024-01-07 22:21

import core.product.fields.order_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_alter_tipodeprodutoatributos_tipo_de_produto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="tipo",
        ),
        migrations.AddField(
            model_name="produto",
            name="tipo_produto",
            field=models.ForeignKey(
                blank=True,
                help_text="Tipo de produto",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="produto",
                to="product.tipodeproduto",
            ),
        ),
        migrations.AlterField(
            model_name="linhadeproduto",
            name="is_active",
            field=models.BooleanField(
                default=False, help_text="Linha de produto ativa", verbose_name="Ativo?"
            ),
        ),
        migrations.AlterField(
            model_name="linhadeproduto",
            name="order",
            field=core.product.fields.order_field.OrderField(
                blank=True, help_text="Ordem da linha de produto", verbose_name="Ordem"
            ),
        ),
        migrations.AlterField(
            model_name="linhadeproduto",
            name="produto_tipo",
            field=models.ForeignKey(
                blank=True,
                help_text="Tipo de produto",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="linha_de_produto",
                to="product.tipodeproduto",
                verbose_name="Tipo de produto",
            ),
        ),
    ]
