# Generated by Django 4.2.7 on 2024-01-07 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_alter_tipodeprodutoatributos_tipo_de_produto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="tipo_produto",
            field=models.ForeignKey(
                default=1,
                help_text="Tipo de produto",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produto",
                to="product.tipodeproduto",
            ),
            preserve_default=False,
        ),
    ]
