# Generated by Django 4.2.7 on 2024-01-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_alter_produto_tipo_produto"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="is_active",
            field=models.BooleanField(default=False, help_text="Categoria ativa"),
        ),
    ]
