# Generated by Django 4.2.7 on 2024-01-14 15:39

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_categoria_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="marca",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="tipo_produto",
        ),
        migrations.AddField(
            model_name="produto",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Data de criação",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produto",
            name="pid",
            field=models.CharField(
                default=datetime.datetime(
                    2024, 1, 14, 15, 39, 0, 568304, tzinfo=datetime.timezone.utc
                ),
                help_text="ID do produto",
                max_length=80,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produto",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="Data de atualização"),
        ),
        migrations.DeleteModel(
            name="Marca",
        ),
    ]
